/* eslint-disable prettier/prettier */

const NOTES = [
    {
        key: 1,
        title: "Réunion 18Hx",
        description: "Nos partenaires et nous-mêmes stockons et/ou accédons à des informations stockées sur un terminal, telles que les cookies, et traitons les données personnelles, telles que les identifiants uniques et les informations standards envoyées par chaque terminal pour diffuser des publicités et du contenu personnalisés, mesurer les performances des publicités et du contenu, obtenir des données d' audience, et développer et améliorer les produits.Avec votre permission, nos partenaires et nous- mêmes pouvons utiliser des données de géolocalisation précises et d’identification par analyse du terminal.En cliquant, vous pouvez consentir aux traitements décrits précédemment.Vous pouvez également accéder à des informations plus détaillées et modifier vos préférences avant de consentir ou pour refuser de donner votre consentement.Veuillez noter que certains traitements de vos données personnelles peuvent ne pas nécessiter votre consentement, mais vous avez le droit de vous y opposer.Vos préférences ne s'appliqueront qu’à ce site web. Vous pouvez modifier vos préférences à tout moment en revenant sur ce site web ou en consultant notre Politique de confidentialité. Nos partenaires et nous-mêmes stockons et/ou accédons à des informations stockées sur un terminal, telles que les cookies, et traitons les données personnelles, telles que les identifiants uniques et les informations standards envoyées par chaque terminal pour diffuser des publicités et du contenu personnalisés, mesurer les performances des publicités et du contenu, obtenir des données d' audience, et développer et améliorer les produits.Avec votre permission, nos partenaires et nous- mêmes pouvons utiliser des données de géolocalisation précises et d’identification par analyse du terminal.En cliquant, vous pouvez consentir aux traitements décrits précédemment.Vous pouvez également accéder à des informations plus détaillées et modifier vos préférences avant de consentir ou pour refuser de donner votre consentement.Veuillez noter que certains traitements de vos données personnelles peuvent ne pas nécessiter votre consentement, mais vous avez le droit de vous y opposer.Vos préférences ne s'appliqueront qu’à ce site web. Vous pouvez modifier vos préférences à tout moment en revenant sur ce site web ou en consultant notre Politique de confidentialité.",
        hour: "2h30"
    },
    {
        key: 2,
        title: "Réunion 18H",
        description: "Nos partenaires et nous-mêmes stockons et/ou accédons à des informations stockées sur un terminal, telles que les cookies, et traitons les données personnelles, telles que les identifiants uniques et les informations standards envoyées par chaque terminal pour diffuser des publicités et du contenu personnalisés, mesurer les performances des publicités et du contenu, obtenir des données d' audience, et développer et améliorer les produits.Avec votre permission, nos partenaires et nous- mêmes pouvons utiliser des données de géolocalisation précises et d’identification par analyse du terminal.En cliquant, vous pouvez consentir aux traitements décrits précédemment.Vous pouvez également accéder à des informations plus détaillées et modifier vos préférences avant de consentir ou pour refuser de donner votre consentement.Veuillez noter que certains traitements de vos données personnelles peuvent ne pas nécessiter votre consentement, mais vous avez le droit de vous y opposer.Vos préférences ne s'appliqueront qu’à ce site web. Vous pouvez modifier vos préférences à tout moment en revenant sur ce site web ou en consultant notre Politique de confidentialité.",
        hour: "2h30"
    },
    {
        key: 3,
        title: "Réunion 18H",
        description: "Nos partenaires et nous-mêmes stockons et/ou accédons à des informations stockées sur un terminal, telles que les cookies, et traitons les données personnelles, telles que les identifiants uniques et les informations standards envoyées par chaque terminal pour diffuser des publicités et du contenu personnalisés, mesurer les performances des publicités et du contenu, obtenir des données d' audience, et développer et améliorer les produits.Avec votre permission, nos partenaires et nous- mêmes pouvons utiliser des données de géolocalisation précises et d’identification par analyse du terminal.En cliquant, vous pouvez consentir aux traitements décrits précédemment.Vous pouvez également accéder à des informations plus détaillées et modifier vos préférences avant de consentir ou pour refuser de donner votre consentement.Veuillez noter que certains traitements de vos données personnelles peuvent ne pas nécessiter votre consentement, mais vous avez le droit de vous y opposer.Vos préférences ne s'appliqueront qu’à ce site web. Vous pouvez modifier vos préférences à tout moment en revenant sur ce site web ou en consultant notre Politique de confidentialité.",
        hour: "2h30"
    },
    {
        key: 4,
        title: "Réunion 18H",
        description: "Nos partenaires et nous-mêmes stockons et/ou accédons à des informations stockées sur un terminal, telles que les cookies, et traitons les données personnelles, telles que les identifiants uniques et les informations standards envoyées par chaque terminal pour diffuser des publicités et du contenu personnalisés, mesurer les performances des publicités et du contenu, obtenir des données d' audience, et développer et améliorer les produits.Avec votre permission, nos partenaires et nous- mêmes pouvons utiliser des données de géolocalisation précises et d’identification par analyse du terminal.En cliquant, vous pouvez consentir aux traitements décrits précédemment.Vous pouvez également accéder à des informations plus détaillées et modifier vos préférences avant de consentir ou pour refuser de donner votre consentement.Veuillez noter que certains traitements de vos données personnelles peuvent ne pas nécessiter votre consentement, mais vous avez le droit de vous y opposer.Vos préférences ne s'appliqueront qu’à ce site web. Vous pouvez modifier vos préférences à tout moment en revenant sur ce site web ou en consultant notre Politique de confidentialité.",
        hour: "2h30"
    },
    {
        key: 5,
        title: "Réunion 18H",
        description: "Nos partenaires et nous-mêmes stockons et/ou accédons à des informations stockées sur un terminal, telles que les cookies, et traitons les données personnelles, telles que les identifiants uniques et les informations standards envoyées par chaque terminal pour diffuser des publicités et du contenu personnalisés, mesurer les performances des publicités et du contenu, obtenir des données d' audience, et développer et améliorer les produits.Avec votre permission, nos partenaires et nous- mêmes pouvons utiliser des données de géolocalisation précises et d’identification par analyse du terminal.En cliquant, vous pouvez consentir aux traitements décrits précédemment.Vous pouvez également accéder à des informations plus détaillées et modifier vos préférences avant de consentir ou pour refuser de donner votre consentement.Veuillez noter que certains traitements de vos données personnelles peuvent ne pas nécessiter votre consentement, mais vous avez le droit de vous y opposer.Vos préférences ne s'appliqueront qu’à ce site web. Vous pouvez modifier vos préférences à tout moment en revenant sur ce site web ou en consultant notre Politique de confidentialité.",
        hour: "2h30"
    },
    {
        key: 6,
        title: "Réunion 18H",
        description: "Nos partenaires et nous-mêmes stockons et/ou accédons à des informations stockées sur un terminal, telles que les cookies, et traitons les données personnelles, telles que les identifiants uniques et les informations standards envoyées par chaque terminal pour diffuser des publicités et du contenu personnalisés, mesurer les performances des publicités et du contenu, obtenir des données d' audience, et développer et améliorer les produits.Avec votre permission, nos partenaires et nous- mêmes pouvons utiliser des données de géolocalisation précises et d’identification par analyse du terminal.En cliquant, vous pouvez consentir aux traitements décrits précédemment.Vous pouvez également accéder à des informations plus détaillées et modifier vos préférences avant de consentir ou pour refuser de donner votre consentement.Veuillez noter que certains traitements de vos données personnelles peuvent ne pas nécessiter votre consentement, mais vous avez le droit de vous y opposer.Vos préférences ne s'appliqueront qu’à ce site web. Vous pouvez modifier vos préférences à tout moment en revenant sur ce site web ou en consultant notre Politique de confidentialité.",
        hour: "2h30"
    },
    {
        key: 7,
        title: "Réunion 18H",
        description: "Nos partenaires et nous-mêmes stockons et/ou accédons à des informations stockées sur un terminal, telles que les cookies, et traitons les données personnelles, telles que les identifiants uniques et les informations standards envoyées par chaque terminal pour diffuser des publicités et du contenu personnalisés, mesurer les performances des publicités et du contenu, obtenir des données d' audience, et développer et améliorer les produits.Avec votre permission, nos partenaires et nous- mêmes pouvons utiliser des données de géolocalisation précises et d’identification par analyse du terminal.En cliquant, vous pouvez consentir aux traitements décrits précédemment.Vous pouvez également accéder à des informations plus détaillées et modifier vos préférences avant de consentir ou pour refuser de donner votre consentement.Veuillez noter que certains traitements de vos données personnelles peuvent ne pas nécessiter votre consentement, mais vous avez le droit de vous y opposer.Vos préférences ne s'appliqueront qu’à ce site web. Vous pouvez modifier vos préférences à tout moment en revenant sur ce site web ou en consultant notre Politique de confidentialité.",
        hour: "2h30"
    },
    {
        key: 8,
        title: "Réunion 18H",
        description: "Nos partenaires et nous-mêmes stockons et/ou accédons à des informations stockées sur un terminal, telles que les cookies, et traitons les données personnelles, telles que les identifiants uniques et les informations standards envoyées par chaque terminal pour diffuser des publicités et du contenu personnalisés, mesurer les performances des publicités et du contenu, obtenir des données d' audience, et développer et améliorer les produits.Avec votre permission, nos partenaires et nous- mêmes pouvons utiliser des données de géolocalisation précises et d’identification par analyse du terminal.En cliquant, vous pouvez consentir aux traitements décrits précédemment.Vous pouvez également accéder à des informations plus détaillées et modifier vos préférences avant de consentir ou pour refuser de donner votre consentement.Veuillez noter que certains traitements de vos données personnelles peuvent ne pas nécessiter votre consentement, mais vous avez le droit de vous y opposer.Vos préférences ne s'appliqueront qu’à ce site web. Vous pouvez modifier vos préférences à tout moment en revenant sur ce site web ou en consultant notre Politique de confidentialité.",
        hour: "2h30"
    },
   
];

export { NOTES };

